name: CowCannon
version: '${project.version}'
main: org.mineacademy.cowcannon.CowCannon
api-version: '1.13'
softdepend: [ Vault, ProtocolLib, PlaceholderAPI, DiscordSRV ]
folia-supported: true
libraries:
  - org.jsoup:jsoup:1.18.3
  - com.theokanning.openai-gpt3-java:service:0.18.2
  - com.sendgrid:sendgrid-java:4.10.3
  - org.openjdk.nashorn:nashorn-core:15.6
  - com.mysql:mysql-connector-j:9.2.0
  - org.xerial:sqlite-jdbc:3.49.1.0
commands:
  cow:
    description: "Spawn an exploding cow"
    usage: "/cow [set/baby] [entityType]"
    aliases: [ cowcannon ]
    permission: cowcannon.command.cow
    permission-message: "You do not have permission to spawn an exploding cow"
  butterfly:
    description: "Toggle particle effect"
    usage: "/butterfly"
    permission: cowcannon.command.butterfly
  displayentity:
    aliases: [ de ]
    description: "Spawns a display entity"
    usage: "/displayentity"
    permission: cowcannon.command.displayentity
  customitem:
    description: "Gives you a custom item"
    usage: "/customitem"
    permission: cowcannon.command.customitem
  gui:
    description: "Opens a GUI"
    usage: "/gui"
    permission: cowcannon.command.gui
  read:
    description: "Reads a webpage from the Internet."
    usage: "/read <url>"
    permission: cowcannon.command.read
  economy:
    description: "Manages Cow economy."
    usage: "/economy <view/take/give> <player> [amount]"
    aliases: [ eco, money, balance, bal ]
    permission: cowcannon.command.economy
  giant:
    description: "Spawns a Giant Boss."
    usage: "/giant"
    permission: cowcannon.command.giant
  psycho:
    description: "Spawns a Psycho custom NMS mob."
    usage: "/psycho"
    permission: cowcannon.command.psycho
  crawl:
    description: "Toggles crawling."
    usage: "/crawl"
    permission: cowcannon.command.crawl
  toast:
    description: "Sends a toast notification."
    usage: "/toast <style> <material> Hello World"
    permission: cowcannon.command.toast
  locale:
    description: "Test player's localization."
    usage: "/locale <get/translate/key>"
    permission: cowcannon.command.locale
  bc:
    description: "Test BungeeCord."
    usage: "/bc"
    permission: cowcannon.command.bungee
  tag:
    description: "Change a player tag above his head."
    usage: "/tag <newTag/reset>"
    permission: cowcannon.command.tag
  hologram:
    description: "Spawn a hologram."
    usage: "/hologram <line1|line2|...>"
    aliases: [ holo ]
    permission: cowcannon.command.hologram
  vanish:
    description: "Vanish a player."
    usage: "/vanish [player]"
    permission: cowcannon.command.vanish
  fly:
    description: "Makes me fly."
    usage: "/fly"
    permission: cowcannon.command.fly
  trade:
    description: "Trade with a villager."
    usage: "/trade <player>"
    permission: cowcannon.command.trade
  region:
    description: "Test WorldGuard region."
    usage: "/region"
    aliases: [ rg ]
    permission: cowcannon.command.region
  ai:
    description: "Test OpenAI GPT-3."
    usage: "/ai <name> <role>"
    permission: cowcannon.command.ai
  email:
    description: "Test email sending."
    usage: "/email <params...>"
    permission: cowcannon.command.email
  javascript:
    aliases: [ js ]
    description: "Test JavaScript."
    usage: "/javascript <script>"
    permission: cowcannon.command.javascript
  database:
    description: "Database command for viewing chat logs."
    aliases: [ db ]
    usage: "/database <view> <player>"
    permission: cowcannon.command.db
permissions:
  cowcannon.command.cow:
    default: op
  cowcannon.cow.use:
    default: true
  cowcannon.command.db:
    default: op