# Exploding animal settings
Explosion:

  # The entity type to explode
  Entity_Type: COW

Tablist:
  Header:
    - <color:#ff8045>First Line</color>
    - <color:#b85c32>Second Line</color>
  Footer:
    - <color:#ff8045>First Footer</color>
    - <color:#b85c32>Second Footer</color>

Database:
  Type: sqlite
  Host: localhost
  Port: 3306
  Database: db
  Username: user
  Password: pass
  SQLite:
    File: sqlite.db